# Generated by Django 5.2 on 2025-05-03 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(choices=[('it', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('employees_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
