# Generated by Django 5.2 on 2025-05-05 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_founded_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees_count',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
